version: "3"
services:
  fluentd:
    build: ./
    volumes:
      - ./conf:/fluentd/etc
      - ./log:/var/log/fluent
    ports:
      - "24224:24224"
      - "24231:24231"
      - "24224:24224/udp"

